// <auto-generated />
using System;
using BlogFinalProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlogFinalProject.Migrations
{
    [DbContext(typeof(BlogUserContext))]
    partial class BlogUserContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0");

            modelBuilder.Entity("BlogFinalProject.Models.BlogUser", b =>
                {
                    b.Property<int>("blogid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("content")
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .HasColumnType("TEXT");

                    b.HasKey("blogid");

                    b.ToTable("BlogUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
